config/routes.rb
Rails.application.routes.draw do
  resources :peeps
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 root "peeps#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/peep.rb
class Peep < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/peeps_controller.rb
class PeepsController < ApplicationController
  before_action :set_peep, only: [:show, :edit, :update, :destroy]

  # GET /peeps
  # GET /peeps.json
  def index
    @peeps = Peep.all.order("created_at DESC")
  end

  # GET /peeps/1
  # GET /peeps/1.json
  def show
  end

  # GET /peeps/new
  def new
    @peep = Peep.new
  end

  # GET /peeps/1/edit
  def edit
  end

  # POST /peeps
  # POST /peeps.json
  def create
    @peep = Peep.new(peep_params)

    respond_to do |format|
      if @peep.save
        format.html { redirect_to @peep, notice: 'Peep was successfully created.' }
        format.json { render :show, status: :created, location: @peep }
      else
        format.html { render :new }
        format.json { render json: @peep.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /peeps/1
  # PATCH/PUT /peeps/1.json
  def update
    respond_to do |format|
      if @peep.update(peep_params)
        format.html { redirect_to @peep, notice: 'Peep was successfully updated.' }
        format.json { render :show, status: :ok, location: @peep }
      else
        format.html { render :edit }
        format.json { render json: @peep.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /peeps/1
  # DELETE /peeps/1.json
  def destroy
    @peep.destroy
    respond_to do |format|
      format.html { redirect_to peeps_url, notice: 'Peep was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_peep
      @peep = Peep.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def peep_params
      params.require(:peep).permit(:peep)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/peeps_helper.rb
module PeepsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChitterChallenge1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
  <div class="notification.is-primary.global-notification">
    <p class="notice"><%= notice %></p>
  </div>
  <% end %>
  <% if flash[:alert] %>
     <div class = "notification.is-danger.global-notification">
       <p class ="alert"><%= alert %></p>
     </div>
     <% end %>
 <nav class="navbar is-info">
       		<div class="navbar-brand">
       		<%= link_to root_path, class: "navbar-item" do %>
       			<h1 class="title is-5">Chitter</h1>
       		<% end %>
     			<div class="navbar-burger burger" data-target="navbarExample">
     					<span></span>
     					<span></span>
     					<span></span>
       		</div>
  </div>

     			<div id="navbarExample" class="navbar-menu">
     				<div class="navbar-end">
  <div class="navbar-item">

   <div class="navbar-item">

         <div class="field is-grouped">
           <p class="control">
             <%= link_to 'New Peep', root_path, class: "button is-info is-inverted" %>
           </p>
         </div>

   </nav>

    <%= yield %>
  </body>
</html>

app/views/peeps/_form.html.erb
<%= form_with(model: peep, local: true) do |form| %>
  <% if peep.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(peep.errors.count, "error") %> prohibited this peep from being saved:</h2>

      <ul>
      <% peep.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :peep %>
    <%= form.text_field :peep %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/peeps/edit.html.erb
<h1>Editing Peep</h1>

<%= render 'form', peep: @peep %>

<%= link_to 'Show', @peep %> |
<%= link_to 'Back', peeps_path %>

app/views/peeps/feed_html.erb
<div class="column is-half">
	<article class="media box">
		<figure class="media-left">
			<p class="image is-64x64">
        <img src="http//bulma.io/images/placeholders/64x64.png">
			 </p>
		</figure>
		<div class="media-content">
			 <%= render 'peeps/form' %>
       
		</div>
	</article>
  <% end %>


<% @peeps.each do | peep | %>
  <div class="box">
  	<article class="media">
  		<div class="media-left">
  			<figure class="image is-64x64">
          <img src="http//bulma.io/images/placeholders/64x64.png">
        </figure>
      </div>

  		<div class="media-content">
  			<div class="content">
          <strong>Yvonne Tang</strong><br />
  				<small><%= @gmail.com %></small><br/>
  				<p><%= peep.peep %></p>
        </div>
  			</div>
      </article>
    </div>
    <% end %>

app/views/peeps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Peeps</h1>

<table>
  <thead>
    <tr>
      <th>Peep</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

<section class="section">
  <div class="container">
    <div class="columns">
      
  </div>

</section>

app/views/peeps/new.html.erb
<h1>New Peep</h1>

<%= render 'form', peep: @peep %>

<%= link_to 'Back', peeps_path %>

app/views/peeps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Peep:</strong>
  <%= @peep.peep %>
</p>

<%= link_to 'Edit', edit_peep_path(@peep) %> |
<%= link_to 'Back', peeps_path %>